scripts:
  beforeStage:
    - yarn update-changelog
    - yarn update-versions
git:
  tagName: 'v${version}',
  tagAnnotation: 'Release v${version}',
  commitMessage: 'Release v${version}'
npm:
  publish: true
