const SECOND = 1
const MINUTE_SECONDS = 60 * SECOND
const HOUR_SECONDS = 60 * MINUTE_SECONDS
const DAY_SECONDS = 24 * HOUR_SECONDS
const YEAR_SECONDS = 365 * DAY_SECONDS

export const MAX_AGE_SHORT = MINUTE_SECONDS
export const MAX_AGE_LONG = YEAR_SECONDS
