name: CI
on:
  pull_request:
    branches:
    - main
    - "*.x"

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn
    - name: Lint
      run: yarn lint
      env:
        CI: true

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn workspace react-app-server build
      env:
        CI: true
